version: '3.8'

services:
  postgresql:
    image: postgres:16
    container_name: smart_kitchen_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smart_kitchen



